# =============================================================
# utils/install_requirements.R
# beescabr -- install everything the pipeline needs, once, on a new machine.
#
#   source("scripts/utils/install_requirements.R")
#
# WHY THIS EXISTS: 23 scripts each installed their own packages and nothing listed the
# whole set, so a fresh machine discovered missing packages one failure at a time.
#
# WHERE THE PIECES LIVE, and why:
#   * the LIST is in config.R -- that is the constants file, and one list means one place
#     to change when a dependency is added;
#   * the INSTALLING is here -- config.R is sourced by every script, so it must not touch
#     the network at load. A setup step should be run deliberately, not as a side effect.
#
# The per-script auto-install blocks stay as a safety net and should rarely fire.
# =============================================================

if (!exists("BEESCABR_PACKAGES")) source("scripts/config.R")

CRAN <- "https://cloud.r-project.org"

# pkgs_missing(): PURE apart from the injected check, so it is testable offline.
pkgs_missing <- function(pkgs, have_fn = function(p) requireNamespace(p, quietly = TRUE)) {
  pkgs[!vapply(pkgs, have_fn, logical(1))]
}

# install_requirements(): install only what is absent, then REPORT what happened.
# Anything still missing afterwards is named rather than swallowed: a silent failure here
# turns into a confusing error much later, in a script that looks unrelated.
install_requirements <- function(pkgs = BEESCABR_PACKAGES,
                                 have_fn = function(p) requireNamespace(p, quietly = TRUE),
                                 install_fn = function(p, ...) install.packages(p, repos = CRAN),
                                 say = message) {
  miss <- pkgs_missing(pkgs, have_fn)
  if (!length(miss)) say("  All ", length(pkgs), " required packages are already installed.")
  else {
    say("  Installing ", length(miss), " missing package(s): ", paste(miss, collapse = ", "))
    for (p in miss) try(install_fn(p), silent = TRUE)
  }
  failed <- pkgs_missing(miss, have_fn)          # still absent after the attempt
  if (length(failed)) {
    say("")
    say("  COULD NOT INSTALL: ", paste(failed, collapse = ", "))
    say("  Some of these need system libraries (sf and pdftools are the usual culprits).")
    say("  On macOS:  brew install gdal proj geos poppler")
  }
  invisible(list(missing = miss, failed = failed))
}

# RUN ON SOURCE. This used to read `#' The package list as a markdown page, grouped the way config.R groups it
#'
#' Generated rather than written, because the list is 39 long and lives in exactly
#' one place. A hand-kept copy drifts the moment a dependency is added -- which is
#' how the retired "optional" list ended up naming packages nothing installed.
#'
#' @param config_path Path to config.R, read for the list and its group comments.
#' @return A character vector of lines, ready to write to dev-docs/PACKAGES.md.
packages_md <- function(config_path = "scripts/config.R") {
  src <- readLines(config_path, warn = FALSE)
  i <- grep("^BEESCABR_PACKAGES <- c\\(", src)[1]
  j <- i; while (!grepl("\\)\\s*$", src[j])) j <- j + 1L

  # A group label is the FIRST line of a comment run. Later lines are that comment
  # continuing, not a new group -- taking the last one made a group called
  # "setup still missing them. One list, everything installed."
  groups <- list(); label <- "other"; in_comment <- FALSE
  for (ln in src[(i + 1L):j]) {
    if (grepl("^\\s*#", ln)) {
      if (!in_comment) { label <- trimws(sub("^\\s*#\\s*", "", ln)); in_comment <- TRUE }
      next
    }
    in_comment <- FALSE
    pk <- regmatches(ln, gregexpr('"[^"]+"', ln))[[1]]
    pk <- gsub('"', "", pk)
    if (length(pk)) groups[[label]] <- c(groups[[label]], pk)
  }
  n <- sum(lengths(groups))

  out <- c("# Packages", "",
           sprintf("**%d packages, one list.** Nothing is optional -- everything the pipeline", n),
           "uses is installed.", "",
           "*Generated -- do not edit this file. The list lives in `config.R`; to change it,",
           "edit `BEESCABR_PACKAGES` there, then run:*", "",
           "```r",
           'INSTALL_SOURCED_FOR_HELPERS <- TRUE   # load the functions without installing',
           'source("scripts/utils/install_requirements.R"); write_packages_md()',
           "```", "",
           "## Install them", "",
           "```r",
           'source("scripts/utils/install_requirements.R")',
           "```", "",
           "It installs only what is missing, then names anything that would not install.",
           "`sf` and `pdftools` are the usual failures, and they need system libraries",
           "rather than R ones -- on macOS, `brew install gdal proj geos poppler`.", "",
           "## The list", "",
           "| What for | Packages |", "|---|---|")
  for (g in names(groups))
    out <- c(out, sprintf("| %s | %s |", g,
                          paste0("`", paste(groups[[g]], collapse = "`, `"), "`")))
  c(out, "",
    "## Adding one", "",
    "Add it to `BEESCABR_PACKAGES` in `config.R`. That is the whole change -- every",
    "script checks the same list through `beescabr_require()`, so there is no second",
    "place to update. Prefer CRAN: a GitHub-only package cannot be installed by",
    "`install_requirements.R` and makes a fresh machine harder to set up.")
}

#' Write dev-docs/PACKAGES.md from the list in config.R
#'
#' @param out Path of the markdown file to write.
#' @param config_path Path to config.R.
#' @return `out`, invisibly.
write_packages_md <- function(out = "dev-docs/PACKAGES.md",
                              config_path = "scripts/config.R") {
  writeLines(packages_md(config_path), out)
  invisible(out)
}

# RUN ON SOURCE. This used to read `if (sys.nframe() == 0)`, meaning "only when this
# is the top-level script" -- but sys.nframe() is 0 only at the true top level and
# source() adds frames, so the documented command
#     source("scripts/utils/install_requirements.R")
# defined these functions and installed nothing, silently. Sourcing IS how this file
# is run; a test that only wants the functions sets the flag below.
if (!exists("INSTALL_SOURCED_FOR_HELPERS")) {
  message("Checking the ", length(BEESCABR_PACKAGES), " packages beescabr needs...")
  install_requirements()
}
