---
title: "bee_data_analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

###### LOAD PACKAGES AND LIBRARIES ######
```{r}
#TEST TEST TEST
#install.packages(c("tidyverse", "dplyr", "ggplot2", "writexl", "egg", "stringr", "lubridate", "rgbif", "gbifdb", "sf"))

library(remotes)
library(tidyverse) #data cleaning
library(dplyr) # data cleaning
library(ggplot2) #to make figures pretty
library(writexl) #
library(egg) #
library(stringr) #
library(lubridate) # to fix the date, and pull the month day and year as separate columns
library(rgbif) #
library(gbifdb) #
library(sf)
library()

install_github("duckdb/duckdb")

# Remote access without downloading data
#gbif <- gbif_remote()
#gbif %>%
  #filter(phylum == "Chordata", year > 1990) %>%
  #count(class, year)


```

###### DATA CLEANING ######
```{r}
getwd()

raw_bee_data <- read.csv("./data/raw_data/CABR_specimens_V4.csv",header=TRUE)

clean_bee_data <- raw_bee_data%>%
  mutate(date_clean = mdy(Date),
        month = month(date_clean),
        day = day(date_clean), 
        year = year(date_clean),
        across(where(is.character), ~na_if(.x, "")))


# Keep ONLY rows where either or NA
#NO LAT OR LONG?
##nolatlong <- clean_bee_data %>%   filter(is.na(Latitude) | is.na(Longitude)) <-- creates whole new data set

##keeps it within the same data set of "clean_bee_data"
clean_bee_data <- clean_bee_data %>% mutate(missinglatlong = is.na(Latitude) | is.na(Longitude))
###filtering it here (filter is default true) will give you true, but best practice to write == True
missinglatlong <- clean_bee_data %>% filter(missinglatlong == TRUE)

#NO GENUS OR SPECIES?
clean_bee_data <- clean_bee_data %>% mutate(missinggenusspecies = is.na(Genus) | is.na(Species))
missinggenusspecies <- clean_bee_data %>% filter(missinggenusspecies == TRUE)

clean_bee_data <- clean_bee_data %>% mutate(missingmethodplant = is.na(Method...Plant))
missingmethodplant <- clean_bee_data %>% filter(missingmethodplant == TRUE)


# SPECIES CHECKLIST
clean_bee_data <- clean_bee_data %>% mutate(oldscientificname = paste0(Genus,"_",Subgenus,"_",Species))

unique_old_species_list <- unique(clean_bee_data$oldscientificname)

view(unique_old_species_list)


```

###### SURVEYS ######
```{r}
transects <- st_read("U:/WILDLIFE/Bees/Bee_Analysis/Bee_Analysis_Project/Bee_Transects.shp")
trails <- c("BST","UPMON","TP","OT")

```



###### BEES ######

##Making Bee Reference Table for SD County, Point Loma, and CABR
```{r}

bee_family <- c("Andrenidae", "Apidae", "Colletidae", "Halictidae", "Megachilidae", "Melittidae", "Stenotritidae")

sd_county_bee_checklist <- read_csv("??")
  # Keep only bee-relevant ranks 
  filter(taxon_rank %in% c("genus", "subgenus", "species", "subspecies")) %>% 
  # Get one row per unique taxon 
  distinct(taxon_id, .keep_all = TRUE) %>% 
  # Select taxonomic columns 
  select( 
    taxon_id,
    taxon_rank, 
    taxon_name,   # the identified name at whatever rank
    taxon_family_name, 
    taxon_genus_name
  ) %>%
arrange(taxon_family_name, taxon_genus_name, taxon_rank, taxon_name)
```




###### PLANTS ######

##Making Plant Reference Table for SD County, Point Loma, and CABR
```{r}
sd_county_plant_checklist <- read_csv("??")
  # Keep only bee-relevant ranks 
  filter(taxon_rank %in% c("genus", "subgenus", "species", "subspecies")) %>% 
  # Get one row per unique taxon 
  distinct(taxon_id, .keep_all = TRUE) %>% 
  # Select taxonomic columns 
  select( 
    taxon_id,
    taxon_rank, 
    taxon_name,   # the identified name at whatever rank
    taxon_family_name, 
    taxon_genus_name
  ) %>%
arrange(taxon_family_name, taxon_genus_name, taxon_rank, taxon_name)
```


```{r}

```

